baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #45762'
disableKinds = ['RSS','sitemap']

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menu.main]]
name = 'Authors'
pageRef = '/authors'
weight = 30

[taxonomies]
author = 'authors'
